switching to a static path

diff --git a/local/update/gce-maintenance/0000-update-kernel b/local/update/gce-maintenance/0000-update-kernel
--- a/local/update/gce-maintenance/0000-update-kernel
+++ b/local/update/gce-maintenance/0000-update-kernel
@@ -16,11 +16,11 @@ if [ $(uname -r | cut -b1) -lt 4 ] ; then
   file1="linux-image-4.4.0-0.bpo.1-amd64_4.4.6-1~bpo8+1_amd64.deb"
   file2="linux-image-amd64_4.4+71~bpo8+1_amd64.deb"
 
-  gsutil cp $(dirname "$GS_EZVM_LOCAL_ARCHIVE")/$file1 "$file1" || fatal $? "Failed to copy: $file1"
-  gsutil cp $(dirname "$GS_EZVM_LOCAL_ARCHIVE")/$file2 "$file2" || fatal $? "Failed to copy: $file2"
+  gsutil cp gs://caster-tv/$file1 /tmp/$file1 || fatal $? "Failed to copy: $file1"
+  gsutil cp gs://caster-tv/$file2 /tmp/$file2 || fatal $? "Failed to copy: $file2"
 
-  dpkg -i $file1 || fatal $? "Failed to dpkg: $file1"
-  dpkg -i $file2 || fatal $? "Failed to dpkg: $file2"
+  dpkg -i /tmp/$file1 || fatal $? "Failed to dpkg: $file1"
+  dpkg -i /tmp/$file2 || fatal $? "Failed to dpkg: $file2"
 
   sudo reboot
 fi
