Fixed gce-startup-reset gcloud commands so they run without needing user input.

diff --git a/local/update/gce-startup-reset/1000-remove-startup-script-metadata b/local/update/gce-startup-reset/1000-remove-startup-script-metadata
--- a/local/update/gce-startup-reset/1000-remove-startup-script-metadata
+++ b/local/update/gce-startup-reset/1000-remove-startup-script-metadata
@@ -20,8 +20,18 @@ case $r in
 esac
 
 if [ "$startup_script_url" != "" ]; then
+
+    zone_ident=$(get_metadata "zone")
+    r=$?
+    case $r in
+        22) ;; # This is a 404 error, as in the zone doesn't exist; no problem.
+        0) ;; # Success we got the zone
+        *) fatal $r "Error querying zone (code=$r)" ;;
+    esac
+    zone=$(echo "$zone_ident" | sed -e 's,.*/zones/,,' -e 's,/.*,,')
+
     instance=$(hostname)
-    cmd="gcloud compute instances remove-metadata $instance --metadata startup-script-url"
+    cmd="gcloud compute instances remove-metadata $instance --zone $zone --keys startup-script-url"
     echo "$cmd"
     sudo $cmd || fatal $? "Failed to remove startup-script-url metadata on instance=$instance"
 fi
diff --git a/local/update/gce-startup-reset/1001-remove-ezvm-updates-metadata b/local/update/gce-startup-reset/1001-remove-ezvm-updates-metadata
--- a/local/update/gce-startup-reset/1001-remove-ezvm-updates-metadata
+++ b/local/update/gce-startup-reset/1001-remove-ezvm-updates-metadata
@@ -17,8 +17,18 @@ case $r in
 esac
 
 if [ "$ezvm_updates" != "" ]; then
+
+    zone_ident=$(get_metadata "zone")
+    r=$?
+    case $r in
+        22) ;; # This is a 404 error, as in the zone doesn't exist; no problem.
+        0) ;; # Success we got the zone
+        *) fatal $r "Error querying zone (code=$r)" ;;
+    esac
+    zone=$(echo "$zone_ident" | sed -e 's,.*/zones/,,' -e 's,/.*,,')
+
     instance=$(hostname)
-    cmd="gcloud compute instances remove-metadata $instance --metadata ezvm-updates"
+    cmd="gcloud compute instances remove-metadata $instance --zone $zone --keys ezvm-updates"
     echo "$cmd"
     sudo $cmd || fatal $? "Failed to remove ezvm-updates metadata on instance=$instance"
 fi
