Create build dir if needed. Now using xclusv/stable branch of bootstrap-salt as we no longer have custom code changes here.

diff --git a/local/update/salt-common/5000-download-salt-bootstrap b/local/update/salt-common/5000-download-salt-bootstrap
--- a/local/update/salt-common/5000-download-salt-bootstrap
+++ b/local/update/salt-common/5000-download-salt-bootstrap
@@ -15,7 +15,12 @@
 
 . "$(dirname "$0")/../../lib.sh" || { echo "Cannot include ../../lib.sh" 1>&2; exit 1; }
 
-URL="https://raw.githubusercontent.com/xclusv/salt-bootstrap/xclusv/bootstrap-salt.sh"
+if [ ! -d $BUILD_DIR ]; then
+    install -d -m 0775 $BUILD_DIR || fatal 1 "Cannot make build dir: $BUILD_DIR"
+fi
+
+#URL="https://raw.githubusercontent.com/xclusv/salt-bootstrap/xclusv/bootstrap-salt.sh"
+URL="https://raw.githubusercontent.com/xclusv/salt-bootstrap/stable/bootstrap-salt.sh"
 CURL_OPTIONS="-L -f --connect-timeout 10"
 
 curl $CURL_OPTIONS $URL -o $BUILD_DIR/bootstrap-salt.sh
